FROM node:20-alpine
WORKDIR /app/frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN addgroup -S dockergroup && adduser -S dockeru -G dockergroup
RUN chown -R dockeru:dockergroup /app/frontend
USER dockeru
EXPOSE 3000
CMD ["npm", "start"]
