services:
  nginx-proxy:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro 
  backend:
    image: harbor.rasamiot.com/internship/project1-backend:${BACKEND_VERSION}
    environment:
      DEBUG: "false"

  frontend:
    image: harbor.rasamiot.com/internship/project1-frontend:${FRONTEND_VERSION}
    environment:
      NODE_ENV: production

