services:
  backend:
    volumes:
      - ./bckend:/app
    environment:
      DEBUG: "true"

  frontend:
    volumes:
      - ./front:/FRONT
      - /FRONT/node_modules
    environment:
      NODE_ENV: development
