services:
  backend:
    image: kianarhnm/backend:1.0.0
    build:
      context: ./bckend
      dockerfile: Dockerfile.prod
    environment:
      DEBUG: "false"

  frontend:
    image: kianarhnm/frontend:1.0.0
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production

