FROM python:3.12-slim
WORKDIR /app/backend
RUN  apt update && apt install -y curl 
RUN groupadd --system prodgroup && \
    useradd --system --gid prodgroup --create-home produser
COPY requirements.txt .
RUN pip install -r requirements.txt 
COPY . .
RUN chown -R produser:prodgroup /app/backend
USER produser
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]

