name: Project1 CI
on:
  push:
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name : Install Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r bckend/requirements.txt

      - name: Test
        run: python bckend/manage.py check

  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps: 
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4

      with: 
        node-version: "20"
    - name: Install Node Dependencies
      run: npm install

    - name: Build  
      run: npm run build
